// Pools de nombres y títulos para enemigos cargados (extraídos del xlsx aprobado por Nox).

export const UNDEAD_NAMES: string[] = [
  "Osgar el Sepultado",
  "Thanuz Cuenca-hueca",
  "Ymir Costilla-rota",
  "Draugr el Ahogado",
  "Ferrum Cráneo-frío",
  "Ossian Ceniza-fría",
  "Vidal Cuenca-vacía",
  "Onfroy el Osario",
  "Ceferino el Yerto",
  "Lúgubre Amadeo",
  "Corvo el Osario",
  "Emeterio Ceniza",
  "Doriano el Marchito",
  "Ubaldo el Yerto",
  "Nino Sudario",
  "Renato Lápida",
  "Melquíades Polvo",
  "Herminia Manos-de-polvo",
  "Casimira la Enterrada",
  "Ludmila la Amortajada",
  "Dahlia Sudario",
  "Ossaria la Hueca",
  "Ombra la Amortajada",
  "Genoveva Mortaja",
  "Dorotea Sudario",
  "Balthazar el Podrido",
  "Baltasar Polvoriento",
  "Gaspar el Amortajado",
  "Anselmo el Amortajado",
  "Odila la Enterrada",
  "Bruno el Enterrado",
  "Fabián Hueso-fino",
  "Herminio Cráneo-partido",
  "Thane Hueso-largo",
  "Asha Ceniza-fría",
  "Iselda Luna-muerta",
  "Nyx Cripta-honda",
  "Draven Sepulcro",
  "Rhogar Lápida",
  "Morgrath Devora-tumbas",
  "Osmundo Polvo-y-hueso",
  "el Sacristán Muerto",
  "el Monje Gris",
  "el Vigía de la Cripta",
  "el Sepulturero Caín",
  "Ostrek Diente-gris",
  "Malvaro el Frío",
  "Nazario el Yacente",
  "Crispín Hueso-roto",
  "Amaranto el Marchito",
  "Bendicto el Podrido",
  "la Hermana Ceniza",
  "Vraad el Descarnado",
  "Corvinus el Frío",
  "el Heraldo Pálido",
  "Nekros el Yacente",
  "Vetusto el Rey Gusano",
  "Marchito el Eterno",
  "el Príncipe Ceniciento",
  "Kaleth Sin-sombra",
  "el Cuervo Osario",
  "Vharok el Rey Yacente",
  "Grendel el Voraz",
  "Sylas Vela-fúnebre",
  "la Condesa Morrigan",
  "Nerissa la Sierpe Muerta",
  "Ramsés el Vendado",
  "Zoser el Cripta-viviente",
  "Absalón Sin-corazón",
  "Melisenda la Fría",
  "Cadmiel el Frío",
  "Baltra el Rey Sepultado",
  "Belisario el Yerto",
  "el Barón de Huesos",
  "Casta la Negra Muerte",
  "Perpetua la Yacente",
  "Rurik Huesos-de-hielo",
  "Sindri Dos-cráneos",
  "el Rey Yacente Osmar",
  "la Novia Cenicienta",
  "Ligeia la Llorona",
  "Solenne la Marchita",
  "el Errante sin Tumba",
  "Wilda la Muda Eterna",
  "la Dama de Blanco",
  "Undín el Ahogado",
  "Serafina la Marchita",
  "la Viuda de Ceniza",
  "Nívea la Sin Pulso",
  "la Doncella Ahogada",
  "Vesper el Sin Voz",
  "Anfitrite la Húmeda",
  "Selim el Errante Muerto",
  "Teobaldo el Mudo Eterno",
  "Sela la Sin Ojos",
  "Elgiva la Amortajada",
  "el Niño de la Cripta",
];
export const BEAST_NAMES: string[] = [
  "Fenrik Colmillo-largo",
  "Úrsel el Zarpas",
  "Ratched Diente-fino",
  "Sarna la Rabiosa",
  "Gnaw el Mordedor",
  "Grull Espalda-erizada",
  "Vix Rabo-cortado",
  "Karr Garra-torcida",
  "Brakk el Colmilludo",
  "Nix Oreja-mordida",
  "Skarn Pellejo-duro",
  "Rume el Aullador",
  "Torv Zarpa-negra",
  "Gash Ojo-amarillo",
  "Hurr el Encorvado",
  "Mott Diente-roto",
  "Brann Pata-coja",
  "Vosk el Sarnoso",
  "Ferox el Hambriento",
  "Lurk Sombra-baja",
  "Snarl la Gruñona",
  "Rask Colmillo-gris",
  "Durn Lomo-ancho",
  "Yowl el Chillón",
  "Grim Zarpa-larga",
  "Nash Diente-curvo",
  "Bristle el Erizado",
  "Maul el Destripador",
  "Vench la Astuta",
  "Grok Puño-peludo",
  "Rhen Ojo-de-fiera",
  "Bram Rompe-cráneos",
  "Threx Garra-doble",
  "Wuff el Grande",
  "Nara Diente-de-sable",
  "Ozzel el Peludo",
  "Crag Espalda-de-piedra",
  "Bane el Feral",
  "Rill Cola-partida",
  "Skag Morro-húmedo",
  "Vorn el Acechante",
  "Kest Uña-larga",
  "Gnar la Baba",
  "Rukh Lomo-negro",
  "Tesk Colmillo-blanco",
  "Ghurl",
  "Vrakk",
  "Mogg",
  "Draska",
  "Skabb",
  "Urgh",
  "Nokk",
  "Brúl",
  "Zarr",
  "Hrogg",
  "Vunk",
  "Grezz",
  "Skorr",
  "Magra",
  "Tholl",
  "Rukk",
  "Vesh",
  "Gnarr",
  "Ozruk",
  "Bhek",
  "Dremm",
  "Kolg",
  "Sruk",
  "Wramm",
  "Yagg",
  "Nhur",
  "Belk",
  "Grosh",
  "Vott",
  "Skree",
  "el Sin Nombre Peludo",
  "la Cosa que Aúlla",
  "Colmillo Coronado",
  "Garra-que-recuerda",
  "el Erguido",
  "la Media-bestia",
  "el Primero en Alzarse",
  "Piel-de-hombre",
  "el Que Camina Erguido",
  "Voz-de-lobo",
  "el Antiguo Aullido",
  "Mano-que-empuña",
  "el Despertado",
  "la Fiera Coronada",
  "Ojo-que-piensa",
  "el Cazador Erguido",
  "Zarpa-de-acero",
  "el Rugido Viejo",
  "Diente-que-habla",
  "la Bestia con Nombre",
  "el Corazón Salvaje",
  "Sangre-de-jauría",
  "el Último Lobo",
  "Garra Real",
  "el Innombrado",
];
export const BANDIT_NAMES: string[] = [
  "Derrik el Tuerto",
  "Baltasar el Sordo",
  "Mara Cuchillo",
  "Orson Cuervo",
  "Ledicia la Zorra",
  "Gaspar Manoslargas",
  "el Sombrío Vael",
  "Ruvik Filoentero",
  "Nadia Ceniza",
  "Corvo el Callado",
  "Brunilda la Torva",
  "Ismael Dientenegro",
  "la Viuda Sela",
  "Tadeo el Marcado",
  "Yorven Sinlengua",
  "Astrid Garfio",
  "el Verdugo Caín",
  "Peregrino el Manco",
  "Solveig la Fría",
  "Malaquías Cuervo",
  "Drago el Rengo",
  "Ferran Trescicatrices",
  "Odila la Falsa",
  "Ansgar el Lobo",
  "Rurik Barbahielo",
  "Elgaros el Errante",
  "Cazio el Rápido",
  "Ingrid Mataperros",
  "Aldo el Príncipe Roto",
  "Vesna la Hueca",
  "Torvald Puñodearena",
  "Nerea la Sierpe",
  "Osmundo el Gris",
  "Kael Sinsombra",
  "Berengario el Cojo",
  "Dálila Nudos",
  "el Cuervo de Hierro",
  "Sindri Dosdagas",
  "Wilda la Muda",
  "Morgrath el Carroñero",
  "Sylas Vela-negra",
  "Thane el Descarnado",
  "Nyx la Silente",
  "Vharok Rompe-yugos",
  "Iselda Media-luna",
  "Grendrick el Voraz",
  "Asha Colmillo",
  "Draven el Hueco",
  "Ombra Ceniza",
  "Rhogar el Quebrado",
  "Beto",
  "Lalo el Navajas",
  "Chuy",
  "Poncho el Gordo",
  "Memo Dedos",
  "Kevin",
  "Toño el Tuerto",
  "Pancho Reyes",
  "Nacho la Sombra",
  "Güicho",
  "Rigo el Feo",
  "Chente Malacara",
  "Fito",
  "el Compa Ramiro",
  "Juan sin Miedo",
  "Pedro el Flaco",
  "Tavo Manazas",
  "Chava el Rápido",
  "Moncho",
  "Beny Cuchillo",
  "Lupe la Brava",
  "Cuco el Silencioso",
  "Nando",
  "Tacho el Cojo",
  "Goyo Barbas",
  "Rosendo el Cuervo",
  "Ivo Media-oreja",
  "Casimiro el Zurdo",
  "Berta Puños",
  "Emeterio Trampas",
  "Ludo el Zarco",
  "Vicente Ceniza",
  "Ondina la Flaca",
  "Anselmo Dosnavajas",
  "Rufo el Mordido",
  "Genoveva Garras",
  "Bruno el Callado",
  "Herminio Malapata",
  "Selim el Errante",
  "Dorotea Filo",
  "Onésimo el Grande",
  "Melquíades Sombra",
  "Ubaldo el Rengo",
  "Prudencio el Manso",
  "Fabián Nudillos",
  "Casta la Negra",
  "Renato Media-luna",
  "Teobaldo el Mudo",
  "Nino Cuchillo",
  "Elías el Zorro Viejo",
];

export const TITLES = {
  blade: ["el Espadachín", "Filo-largo", "el Cortante", "Mano-de-acero", "Dos-filos", "el Tajador", "Acero-vivo"],
  blunt: ["el Rompehuesos", "Machaca", "el Aplastador", "Quiebra-yelmos", "el Mazo", "Cráneo-roto"],
  thief: ["el Ratero", "Dedos-ligeros", "Manoslargas", "el Bolsas", "el Sisa", "el Codicioso", "el Embrujado", "Susurros", "el Marcado", "el Maldito", "Ceniza-viva", "el Coronado"],
  generic: ["el Raso", "el Común", "sin renombre", "el Novato", "el Cualquiera"],
};
